# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
warnings_are_errors: true
r: bioc-devel
bioc_check: true
sudo: false
cache: packages

before_script:
  - R -e 'BiocManager::install(version = "devel", ask=FALSE)'
  - R -e 'BiocManager::valid()'

os:
  - linux
  - osx

r:
  - 4.0
  - release
  - devel
